# Generated by Django 4.2.6 on 2023-12-29 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sesiones', '0005_alter_solicitud_fecha'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitud',
            old_name='motivo',
            new_name='motivs',
        ),
    ]
