# Generated by Django 4.2.6 on 2023-12-29 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sesiones', '0006_rename_motivo_solicitud_motivs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitud',
            old_name='motivs',
            new_name='motivo',
        ),
    ]
