# Generated by Django 4.2.6 on 2023-12-29 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesiones', '0007_rename_motivs_solicitud_motivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atencion',
            name='fecha',
            field=models.DateTimeField(null=True),
        ),
    ]
