# Generated by Django 4.2.6 on 2023-12-29 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesiones', '0008_alter_atencion_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesion',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
