# Generated by Django 4.2.6 on 2023-12-29 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesiones', '0009_alter_sesion_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='estado',
            field=models.CharField(choices=[('Nulo', 'No especifica'), ('Nuevo', 'Nuevo'), ('Usado', 'Usado')], max_length=25),
        ),
    ]
