# Generated by Django 4.2.6 on 2023-12-29 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesiones', '0010_alter_insumo_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='nombre',
            field=models.CharField(max_length=25),
        ),
    ]
